#name: Prosenjit Kundu, Horrible Cop
markdown: kramdown
permalink: /blog/:year/:month/:day/:title

title: better Health using AI
email: bHAI@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Site is under construction.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: bHAI
github_username:  bHAI
